version: '3.8'

services:
  steem_lb:
    container_name: ${DOCKER_IMAGE}
    image: ${DOCKER_IMAGE}
    build:
      context: .
      dockerfile: Dockerfile    
    restart: on-failure:${RETRY_COUNT}
    ports:
      - "${STEEM_LB_PORT}:9091"
    environment:
      - NODE_ENV=${NODE_ENV}
      - SSL_CERT_PATH=${SSL_CERT_PATH}
      - SSL_KEY_PATH=${SSL_KEY_PATH}
      - CACHE_ENABLED=${CACHE_ENABLED}
      - CACHE_TTL=${CACHE_TTL}
      - STEEM_LB_VERSION=${STEEM_LB_VERSION}
      - DEBUG=${DEBUG}
    volumes:
      - /root/.acme.sh/:/root/.acme.sh/
      - ./config.yaml:/app/config.yaml
